package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbAdmNucleo generated by hbm2java
 */
public class TbAdmNucleo implements java.io.Serializable {

	

	private String vrIdnucleo;
	private TbAdmDependencia tbAdmDependencia;
	private String vrNombre;
	private String vrAlias;
	private TbAdmPersona vrResponsable;
	private String vrModusuario;
	private Date vrModfecha;	
	private Set tbAdmMateriases = new HashSet(0);

	public TbAdmNucleo() {
		super();
	}	
	
	public TbAdmNucleo(String vrIdnucleo, TbAdmDependencia tbAdmDependencia,
			String vrNombre, String vrModusuario, Date vrModfecha) {
		super();
		this.vrIdnucleo = vrIdnucleo;
		this.tbAdmDependencia = tbAdmDependencia;
		this.vrNombre = vrNombre;
		this.vrModusuario = vrModusuario;
		this.vrModfecha = vrModfecha;
	}

	public TbAdmNucleo(String vrIdnucleo, TbAdmDependencia tbAdmDependencia,
			String vrNombre, String vrAlias, TbAdmPersona vrResponsable,
			String vrModusuario, Date vrModfecha) {
		super();
		this.vrIdnucleo = vrIdnucleo;
		this.tbAdmDependencia = tbAdmDependencia;
		this.vrNombre = vrNombre;
		this.vrAlias = vrAlias;
		this.vrResponsable = vrResponsable;
		this.vrModusuario = vrModusuario;
		this.vrModfecha = vrModfecha;
	}

	public TbAdmNucleo(String vrIdnucleo, TbAdmDependencia tbAdmDependencia) {
		this.vrIdnucleo = vrIdnucleo;
		this.tbAdmDependencia = tbAdmDependencia;
	}

	public TbAdmNucleo(String vrIdnucleo, TbAdmDependencia tbAdmDependencia,
			String vrNombre, String vrModusuario, Date vrModfecha,
			Set tbAdmMateriases) {
		this.vrIdnucleo = vrIdnucleo;
		this.tbAdmDependencia = tbAdmDependencia;
		this.vrNombre = vrNombre;
		this.vrModusuario = vrModusuario;
		this.vrModfecha = vrModfecha;
		this.tbAdmMateriases = tbAdmMateriases;
	}

	public String getVrIdnucleo() {
		return this.vrIdnucleo;
	}

	public void setVrIdnucleo(String vrIdnucleo) {
		this.vrIdnucleo = vrIdnucleo;
	}

	public TbAdmDependencia getTbAdmDependencia() {
		return this.tbAdmDependencia;
	}

	public void setTbAdmDependencia(TbAdmDependencia tbAdmDependencia) {
		this.tbAdmDependencia = tbAdmDependencia;
	}

	public String getVrNombre() {
		return this.vrNombre;
	}

	public void setVrNombre(String vrNombre) {
		this.vrNombre = vrNombre;
	}
	
	public String getVrAlias() {
		return vrAlias;
	}

	public void setVrAlias(String vrAlias) {
		this.vrAlias = vrAlias;
	}

	public TbAdmPersona getVrResponsable() {
		return vrResponsable;
	}

	public void setVrResponsable(TbAdmPersona vrResponsable) {
		this.vrResponsable = vrResponsable;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getVrModfecha() {
		return this.vrModfecha;
	}

	public void setVrModfecha(Date vrModfecha) {
		this.vrModfecha = vrModfecha;
	}

	
	public Set getTbAdmMateriases() {
		return this.tbAdmMateriases;
	}

	public void setTbAdmMateriases(Set tbAdmMateriases) {
		this.tbAdmMateriases = tbAdmMateriases;
	}

}
