package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Set;

/**
 * TbAdmMaterias generated by hbm2java
 */
public class TbAdmMateria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String vrIdmateria;
	private TbAdmNucleo tbAdmNucleo;
	private TbAdmArea tbAdmArea;
	private String vrNombre;
	private int nbSemestre;
	private int nbCreditos;
	private int blHabilitable;
	private int blValidable;
	private int blClasificable;
	private int nbHt;
	private int nbHp;
	private int nbHtp;
	private String vrAlias;
	private String vrModusuario;
	private Date dtModfecha;
	private int blEstado;

	public TbAdmMateria() {
	}

	public TbAdmMateria(String vrIdmateria, TbAdmNucleo tbAdmNucleo,
			int nbSemestre) {
		this.vrIdmateria = vrIdmateria;
		this.tbAdmNucleo = tbAdmNucleo;
		this.nbSemestre = nbSemestre;
	}


	public TbAdmMateria(String vrIdmateria, TbAdmNucleo tbAdmNucleo,
			TbAdmArea tbAdmArea, String vrNombre, int nbSemestre,
			int nbCreditos, int blHabilitable, int blValidable,
			int blClasificable, int nbHt, int nbHp, int nbHtp, String vrAlias,
			String vrModusuario, Date dtModfecha, int blEstado) {
		super();
		this.vrIdmateria = vrIdmateria;
		this.tbAdmNucleo = tbAdmNucleo;
		this.tbAdmArea = tbAdmArea;
		this.vrNombre = vrNombre;
		this.nbSemestre = nbSemestre;
		this.nbCreditos = nbCreditos;
		this.blHabilitable = blHabilitable;
		this.blValidable = blValidable;
		this.blClasificable = blClasificable;
		this.nbHt = nbHt;
		this.nbHp = nbHp;
		this.nbHtp = nbHtp;
		this.vrAlias = vrAlias;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
		this.blEstado = blEstado;
	}

	@SuppressWarnings("rawtypes")
	public TbAdmMateria(String vrIdmateria, TbAdmNucleo tbAdmNucleo,
			String vrNombre, int nbSemestre, int nbCreditos,
			int blHabilitable, int blValidable,
			int blClasificable, int nbHt, int nbHp,
			int nbHtp, String vrModusuario, Date dtModfecha,
			int blEstado, Set tbMicMicrocurriculo,
			Set tbMicMateriasxpensums, Set tbAdmPrerrequisitosesForVrMateria,
			Set tbAdmCorrequisitosesForVrCorrequisito,
			Set tbAdmPrerrequisitosesForVrPrerrequisito,
			Set tbAdmCorrequisitosesForVrMateria) {
		this.vrIdmateria = vrIdmateria;
		this.tbAdmNucleo = tbAdmNucleo;
		this.vrNombre = vrNombre;
		this.nbSemestre = nbSemestre;
		this.nbCreditos = nbCreditos;
		this.blHabilitable = blHabilitable;
		this.blValidable = blValidable;
		this.blClasificable = blClasificable;
		this.nbHt = nbHt;
		this.nbHp = nbHp;
		this.nbHtp = nbHtp;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
		this.blEstado = blEstado;
//		this.tbMicMicrocurriculo = tbMicMicrocurriculo;
//		this.tbMicMateriasxpensums = tbMicMateriasxpensums;
//		this.tbAdmPrerrequisitosesForVrMateria = tbAdmPrerrequisitosesForVrMateria;
//		this.tbAdmCorrequisitosesForVrCorrequisito = tbAdmCorrequisitosesForVrCorrequisito;
//		this.tbAdmPrerrequisitosesForVrPrerrequisito = tbAdmPrerrequisitosesForVrPrerrequisito;
//		this.tbAdmCorrequisitosesForVrMateria = tbAdmCorrequisitosesForVrMateria;
	}

	public String getVrIdmateria() {
		return this.vrIdmateria;
	}

	public void setVrIdmateria(String vrIdmateria) {
		this.vrIdmateria = vrIdmateria;
	}

	public TbAdmNucleo getTbAdmNucleo() {
		return this.tbAdmNucleo;
	}

	public void setTbAdmNucleo(TbAdmNucleo nucleo) {
		this.tbAdmNucleo = nucleo;
	}

	public String getVrNombre() {
		return this.vrNombre;
	}

	public void setVrNombre(String vrNombre) {
		this.vrNombre = vrNombre;
	}

	public int getNbSemestre() {
		return this.nbSemestre;
	}

	public void setNbSemestre(int nbSemestre) {
		this.nbSemestre = nbSemestre;
	}

	public int getNbCreditos() {
		return this.nbCreditos;
	}

	public void setNbCreditos(int nbCreditos) {
		this.nbCreditos = nbCreditos;
	}

	public int getBlHabilitable() {
		return this.blHabilitable;
	}

	public void setBlHabilitable(int blHabilitable) {
		this.blHabilitable = blHabilitable;
	}

	public int getBlValidable() {
		return this.blValidable;
	}

	public void setBlValidable(int blValidable) {
		this.blValidable = blValidable;
	}

	public int getBlClasificable() {
		return this.blClasificable;
	}

	public void setBlClasificable(int blClasificable) {
		this.blClasificable = blClasificable;
	}

	public int getNbHt() {
		return this.nbHt;
	}

	public void setNbHt(int nbHt) {
		this.nbHt = nbHt;
	}

	public int getNbHp() {
		return this.nbHp;
	}

	public void setNbHp(int nbHp) {
		this.nbHp = nbHp;
	}

	public int getNbHtp() {
		return this.nbHtp;
	}

	public void setNbHtp(int nbHtp) {
		this.nbHtp = nbHtp;
	}
	
	

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}

	public int getBlEstado() {
		return this.blEstado;
	}

	public void setBlEstado(int blEstado) {
		this.blEstado = blEstado;
	}
	
	public TbAdmArea getTbAdmArea() {
		return tbAdmArea;
	}

	public void setTbAdmArea(TbAdmArea tbAdmArea) {
		this.tbAdmArea = tbAdmArea;
	}
	
	public String getVrAlias() {
		return vrAlias;
	}

	public void setVrAlias(String vrAlias) {
		this.vrAlias = vrAlias;
	}

	}
