package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbAdmTipopersona generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbAdmTipopersona implements java.io.Serializable {

	private int nbId;
	private TbAdmPersona vrPersona;
	private String vrDescripcion;
	private String vrNivel;
	private String vrModusuario;
	private Date dtModfecha;
	
	
	public TbAdmTipopersona() {
		super();
	}

	public TbAdmTipopersona(int nbId) {
		super();
		this.nbId = nbId;
	}

	public TbAdmTipopersona(int nbId, TbAdmPersona vrPersona,
			String vrDescripcion) {
		super();
		this.nbId = nbId;
		this.vrPersona = vrPersona;
		this.vrDescripcion = vrDescripcion;
	}

	public TbAdmTipopersona(int nbId, TbAdmPersona vrPersona,
			String vrDescripcion, String vrModusuario, Date dtModfecha) {
		super();
		this.nbId = nbId;
		this.vrPersona = vrPersona;
		this.vrDescripcion = vrDescripcion;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
	}


	public int getNbId() {
		return nbId;
	}

	public void setNbId(int nbId) {
		this.nbId = nbId;
	}

	public TbAdmPersona getVrPersona() {
		return vrPersona;
	}

	public void setVrPersona(TbAdmPersona vrPersona) {
		this.vrPersona = vrPersona;
	}

	public String getVrDescripcion() {
		return this.vrDescripcion;
	}

	public void setVrDescripcion(String vrDescripcion) {
		this.vrDescripcion = vrDescripcion;
	}

	public String getVrNivel() {
		return vrNivel;
	}

	public void setVrNivel(String vrNivel) {
		this.vrNivel = vrNivel;
	}
	
	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}
}
