package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Set;

/**
 * TbMicTemas generated by hbm2java
 */
public class TbMicTema implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int nbIdtema;
	private String vrDescripcion;
	private String vrModusuario;
	private Date dtModfecha;
	
	public TbMicTema() {
		super();
	}

	public TbMicTema(String vrDescripcion, String vrModusuario, Date dtModfecha) {
		super();
		this.vrDescripcion = vrDescripcion;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
	}



	@SuppressWarnings("rawtypes")
	public TbMicTema(int nbIdtema, String vrDescripcion,
			String vrModusuario, Date dtModfecha, Set tbMicSubtemases,
			Set tbMicTemasxunidads) {
		this.nbIdtema = nbIdtema;
		this.vrDescripcion = vrDescripcion;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
//		this.tbMicSubtemases = tbMicSubtemases;
//		this.tbMicTemasxunidads = tbMicTemasxunidads;
	}

	public int getNbIdtema() {
		return this.nbIdtema;
	}

	public void setNbIdtema(int nbIdtema) {
		this.nbIdtema = nbIdtema;
	}

	public String getVrDescripcion() {
		return this.vrDescripcion;
	}

	public void setVrDescripcion(String vrDescripcion) {
		this.vrDescripcion = vrDescripcion;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}

	}
